export const SET_ALBUMS = 'SET_ALBUMS';
export const ADD_NEW_ALBUM = 'ADD_NEW_ALBUM';

export const SET_CURRENT_ALBUM = 'SET_CURRENT_ALBUM';
export const SET_CURRENT_ALBUM_PHOTOS = 'SET_CURRENT_ALBUM_PHOTOS';